name: cunning_document_scanner
description: A document scanner plugin for flutter. Scan and crop automatically on iOS and Android.
version: 1.2.2
homepage: https://cunning.biz
repository: https://github.com/jachzen/cunning_document_scanner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.2.1
  permission_handler_platform_interface: ^4.1.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <5.0.0"
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: biz.cunning.cunning_document_scanner
        pluginClass: CunningDocumentScannerPlugin
      ios:
        pluginClass: CunningDocumentScannerPlugin
